### ISSUE TITLE
Week 3  Day 4 morning session

### ISSUE THREAD

**Issue by bill7pearl** [annaeliana7/Portfolio#8]

**Comment by bill7pearl** [comment]
Good implementations overall, however, you may change some margins in the projects sections as follows:
![issueAnna](https://user-images.githubusercontent.com/77294268/201026756-9b7b9133-6647-405f-8e81-a98a0d166680.jpg)
You could set the img width property to 50%.

**Comment by annaeliana7** [comment]
Thank you for your review and for the recommendations. 🌟 🌟 ⭐  Changes have been made. 🚀 🥇
